# Generated by Django 5.2.9 on 2025-12-11 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='to_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
