# Generated by Django 5.2.9 on 2025-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_pendingadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingadmission',
            name='payment_mode',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('EMI', 'EMI (PDC Required)'), ('LOAN', 'Student Loan')], default='FULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingadmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
