# Generated by Django 5.2.9 on 2025-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_admissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrequest',
            name='payment_mode',
            field=models.CharField(choices=[('full', 'Full Payment'), ('emi', 'Booking Fee + EMI'), ('loan', 'Education Loan / PDC')], default='full', max_length=10),
        ),
    ]
