# Generated by Django 5.2.9 on 2025-12-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_pendingadmission_payment_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='subject',
            new_name='exam_name',
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='passed',
            new_name='is_passed',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='marks',
        ),
        migrations.AddField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
