# Generated by Django 5.2.9 on 2025-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0008_remove_student_batch_no_batch_course_batch_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedback',
            old_name='submitted_at',
            new_name='date_submitted',
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('Course', 'Course Content'), ('Trainer', 'Trainer/Teaching'), ('Facility', 'Infrastructure/Facility'), ('Other', 'Other')], default='Course', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
