# Generated by Django 5.2.9 on 2025-12-30 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0009_rename_submitted_at_studentfeedback_date_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(help_text='e.g., Python Basics, Django Views', max_length=200)),
                ('type', models.CharField(choices=[('Note', 'PDF / Document'), ('Video', 'Video / Link'), ('Assignment', 'Assignment / Task')], default='Note', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='classroom/materials/')),
                ('link', models.URLField(blank=True, help_text='Paste YouTube or Resource Link here', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Leave blank if this is for the whole course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentApp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='StudentApp.course')),
            ],
        ),
    ]
