# Generated by Django 5.2.9 on 2025-12-30 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0010_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='examresult',
            name='date_conducted',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='StudentApp.student'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
