# Generated by Django 5.2.9 on 2025-12-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0011_remove_examresult_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_of_drive', models.DateTimeField()),
                ('venue', models.CharField(help_text='Online Link or Physical Address', max_length=200)),
                ('eligibility_criteria', models.TextField(help_text='e.g. Min 60% marks, Python completed')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(help_text='Expected return date')),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Issued', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
