# Generated by Django 5.2.9 on 2025-12-30 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0012_placementdrive_bookissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='e.g. Django Views, Python Intro', max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Meet Link for Online Class', null=True)),
                ('room_number', models.CharField(blank=True, help_text='For Offline Class', max_length=50, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='StudentApp.batch')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentApp.trainer')),
            ],
        ),
    ]
