# Generated by Django 5.2.9 on 2025-12-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0013_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='e.g. Unit 1: Introduction', max_length=200)),
                ('topic', models.CharField(help_text='e.g. Variables & Data Types', max_length=200)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of the topic in the course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='StudentApp.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.batch')),
                ('syllabus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.syllabus')),
            ],
        ),
    ]
