# Generated by Django 5.2.9 on 2025-12-30 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0014_syllabus_batchprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='student',
        ),
        migrations.AddField(
            model_name='pendingadmission',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingadmission',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingadmission',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingadmission',
            name='payment_receipt',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='eligibility_criteria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='venue',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentApp.batch'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Placement',
        ),
    ]
