# Generated by Django 5.2.9 on 2025-12-30 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0015_remove_placement_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-date_paid']},
        ),
        migrations.AddField(
            model_name='feepayment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name for Cheque/Loan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Date written on the Cheque (for PDC)', null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_type',
            field=models.CharField(choices=[('BOOKING', 'Booking / Seat Reservation'), ('ADMISSION', 'Admission / Tuition Fee'), ('EXAM', 'Exam Fee'), ('OTHER', 'Fine / Other')], default='ADMISSION', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True, help_text="e.g. 'EMI Installment 1 of 3'", null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (PDC / Uncleared)'), ('CLEARED', 'Cleared / Received'), ('BOUNCED', 'Bounced / Failed'), ('REFUNDED', 'Refunded')], default='CLEARED', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='UPI Ref / Loan App No / DD No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booking Paid', 'Booking Paid'), ('Partial', 'Partially Paid'), ('Fully Paid', 'Fully Paid'), ('Overdue', 'Overdue (PDC Bounced/Late)')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fee_committed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total agreed fee for this student', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when transaction happened'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online (UPI/Card/NetBanking)'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque / PDC'), ('LOAN', 'Education Loan Disbursement'), ('DD', 'Demand Draft')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='StudentApp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_fee_paid',
            field=models.BooleanField(default=False, help_text='True only if fully paid'),
        ),
    ]
