# Generated by Django 5.2.9 on 2025-12-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0016_alter_feepayment_options_feepayment_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booking Paid', 'Booking Paid'), ('Partial', 'Partially Paid'), ('Fully Paid', 'Fully Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI / GPay / PhonePe'), ('Bank Transfer', 'Bank Transfer (NEFT/IMPS)'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('CLEARED', 'Cleared / Successful'), ('BOUNCED', 'Bounced / Failed')], default='CLEARED', max_length=20)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='StudentApp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
    ]
