# Generated by Django 5.2.9 on 2025-12-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0017_alter_student_fee_status_payment_delete_feepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fee_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fee_committed',
        ),
        migrations.AlterField(
            model_name='student',
            name='is_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('FULL', 'Full Payment'), ('EMI', 'EMI'), ('LOAN', 'Loan')], max_length=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('receipt_file', models.FileField(blank=True, upload_to='receipts/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
