# Generated by Django 5.2.9 on 2026-01-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0018_remove_student_fee_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='timetable_link',
        ),
        migrations.AddField(
            model_name='batch',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentApp.trainer'),
        ),
    ]
