# Generated by Django 5.2.9 on 2026-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0019_remove_batch_timetable_link_batch_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='6 Months', max_length=50),
        ),
    ]
