# Generated by Django 5.2.8 on 2026-01-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0020_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_card_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='lms_access_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='welcome_kit_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp_group_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='StudentApp.course'),
        ),
    ]
