# Generated by Django 5.2.9 on 2026-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('One-Time', 'One-Time'), ('Installment', 'Installment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. B.Tech, MCA, 12th', max_length=100, null=True),
        ),
    ]
