# Generated by Django 5.2.9 on 2026-01-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdmApp', '0002_lead_age_lead_gender_lead_payment_type_and_more'),
        ('StudentApp', '0019_remove_batch_timetable_link_batch_time_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='StudentApp.student')),
            ],
        ),
    ]
